version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ingestion-engine-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  # <-- Mount SQL folder
    restart: always

  redis:
    image: redis:7-alpine
    container_name: ingestion-engine-redis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: ingestion-engine-app
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/fleet_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'









# version: '3.8'

# services:
#   redis:
#     image: redis:7-alpine
#     container_name: ingestion-engine-redis
#     ports:
#       - '6379:6379'
#     restart: always
#     command: redis-server --appendonly yes
