version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ingestion-engine-redis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --appendonly yes






# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: fleet_user
#       POSTGRES_PASSWORD: fleet_pass
#       POSTGRES_DB: fleet_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   app:
#     build: .
#     command: npm run start:dev
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://fleet_user:fleet_pass@db:5432/fleet_db

# volumes:
#   pgdata:
